/* Datos extraidos de modal-data.js: missionReferentes */
(function(){
'use strict';
window.missionReferentes = {
    m1_1: {
      tipo: 'Mision material - Naturaleza para la Vida',
      titulo: 'Paises Bajos - Gestion Delta del Rin/Mosa',
      resumen: 'Tipo de caso: Gestión hídrica integral y adaptación climática. Problema equivalente: Territorio bajo el nivel del mar con riesgo permanente de inundaciones y gestión compleja de cuencas compartidas. ¿Qué hicieron?: Crearon un sistema nacional de gobernanza del agua (Waterboards) con presupuesto propio, planificación a 100 años y el programa Delta Works / Room for the River. Integraron soluciones de infraestructura dura (diques, compuertas) con soluciones basadas en la naturaleza (llanuras de inundación, retiro de diques). Plataforma Delta de innovación público-privada. Instrumento central: Autoridades de cuenca autónomas con mandato legal, financiamiento parafiscal territorial y gestión adaptativa multinivel. Resultados verificados: Reducción del riesgo de inundación en un 99%; modelo exportado a 60 países; generó una industria de ingeniería hídrica de USD 18.000 millones anuales. Lección transferible a Santander: Santander puede crear autoridades de cuenca con mandato y presupuesto propio para las 7 cuencas estratégicas. El modelo Waterboard es directamente transferible al diseño del P01 (Plan Maestro Hídrico). Conexión en Santander 2050: P01 Plan Maestro Hídrico · P04 Red de monitoreo · Motor B (Bioeconomía).',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'Delta Programme (Fuente 1)', url: 'https://english.deltaprogramma.nl/', nota: 'Programa marco de gestion del delta.' },
        { titulo: 'Rijkswaterstaat (Fuente 2)', url: 'https://www.rijkswaterstaat.nl/en/expertise/water', nota: 'Gestion operacional del agua en Paises Bajos.' }
      ]
    },
    m1_2: {
      tipo: 'Mision material - Naturaleza para la Vida',
      titulo: 'Costa Rica - FONAFIFO y servicios ecosistemicos',
      resumen: 'Tipo de caso: Servicios ecosistémicos y restauración productiva. Problema equivalente: Deforestación masiva en los años 80 que redujo la cobertura forestal al 21%, con pérdida de cuencas, biodiversidad y base productiva rural. ¿Qué hicieron?: En 1996 crearon el FONAFIFO con base legal nacional, que paga directamente a propietarios privados y comunidades por conservar bosques, reforestar y gestionar agroforestería. Financiado por impuesto a combustibles, ventas de bonos de carbono y cooperación internacional. Hoy gestiona más de 1 millón de hectáreas. Instrumento central: Fondo territorial de PSE con base legal, financiamiento mixto (parafiscal + carbono + cooperación) y contrato directo con productores. Resultados verificados: Cobertura forestal aumentó del 21% al 60% en 30 años. USD 500 millones pagados a comunidades rurales. Carbono-neutralidad declarada y turismo ecológico de USD 4.000 millones anuales. Lección transferible a Santander: El modelo FONAFIFO es el referente más directo para el P02 (Fondo Territorial PSE) de Santander. Los mecanismos de contrato, verificación y pago a comunidades son replicables con adaptaciones mínimas. Conexión en Santander 2050: P02 Fondo PSE · P03 Restauración cuencas · P06 Páramos · Motor B.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'FONAFIFO (Fuente 1)', url: 'https://www.fonafifo.go.cr/es/', nota: 'Modelo institucional de incentivos ambientales.' },
        { titulo: 'PNUD Costa Rica (Fuente 2)', url: 'https://www.undp.org/costa-rica', nota: 'Contexto de cooperacion para sostenibilidad.' }
      ]
    },
    m1_3: {
      tipo: 'Mision material - Naturaleza para la Vida',
      titulo: 'Water Funds TNC en America Latina',
      resumen: 'Tipo de caso: Gobernanza de cuencas, financiamiento mixto y pagos por servicios hídricos. Problema equivalente: Ciudades y empresas latinoamericanas con suministro de agua amenazado por deforestación y degradación de cuencas abastecedoras, sin mecanismo financiero que conecte a los beneficiarios urbanos con los guardianes rurales del agua. ¿Qué hicieron?: Desde 2000, TNC impulsó los Water Funds: fondos fiduciarios que capturan pagos de empresas de agua, industrias y gobiernos municipales, y los transfieren como incentivos económicos a comunidades campesinas e indígenas que conservan las cuencas abastecedoras. El Fondo del Agua de Quito (FONAG) fue el primero; hoy operan 38 fondos en 17 países de América Latina. Cada fondo tiene gobernanza multiactor: empresa de agua + municipio + empresas privadas + comunidades. Los criterios de pago son verificados con monitoreo hidrológico independiente. Instrumento central: Fondo fiduciario multiactor con gobernanza territorial, financiamiento continuo de beneficiarios del agua, monitoreo hidrológico independiente y pago directo a comunidades guardianas. Resultados verificados: Más de USD 300 millones movilizados en 20 años. FONAG protege las cuencas que abastecen a 3 millones de habitantes de Quito. El modelo ha reducido costos de tratamiento de agua en un 30% en ciudades participantes. Replicado en Bogotá (Fondo Agua por la Vida), Medellín, Lima y São Paulo. Lección transferible a Santander: Es el referente geográfica e institucionalmente más cercano para el P02 (Fondo Territorial PSE) de Santander. El modelo FONAG puede adaptarse directamente para las cuencas que abastecen al AMB (Río de Oro, Suratá), articulando CDMB, Acueducto Metropolitano, empresas del AMB y comunidades campesinas de Soto Norte y Guanentá. Conexión en Santander 2050: P02 Fondo PSE · P01 Plan Maestro Hídrico · P06 Páramos · SB1 BioRegión · Motor B.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'The Nature Conservancy - Water Funds (Fuente 1)', url: 'https://www.nature.org/en-us/about-us/where-we-work/latin-america/', nota: 'Marco y casos regionales de fondos hidricos.' },
        { titulo: 'Water Funds Toolbox (Fuente 2)', url: 'https://resilientwatershedstoolbox.org/', nota: 'Guias para diseno e implementacion.' }
      ]
    },
    m1_4: {
      tipo: 'Mision material - Naturaleza para la Vida',
      titulo: 'Israel - Gestion hidrica en escasez extrema',
      resumen: 'Tipo de caso: Eficiencia hídrica, reutilización y tecnología para zonas de escasez. Problema equivalente: País con el 60% de su territorio en zonas áridas o semiáridas, sin ríos perennes significativos, con alta densidad poblacional y necesidad de sostener una agricultura intensiva con disponibilidad hídrica mínima. ¿Qué hicieron?: Construyeron el sistema hídrico más eficiente del mundo: riego por goteo a escala nacional (inventado en Israel), desalinización del 80% del agua potable (5 plantas nacionales), reutilización del 87% de las aguas residuales para agricultura (el porcentaje más alto del mundo), y gestión centralizada de toda el agua nacional a través de Mekorot con monitoreo en tiempo real. Todo el sistema de agua es gestionado como infraestructura crítica de Estado, con tarifas que reflejan el costo real del recurso. Instrumento central: Gestión centralizada del agua como bien estratégico de Estado, inversión masiva en tecnología de eficiencia (goteo, desalinización, reutilización), tarifación real del agua y plataforma de monitoreo nacional en tiempo real. Resultados verificados: Israel produce el 20% de sus exportaciones agrícolas en zonas desérticas. Consumo de agua per cápita reducido en un 30% en 20 años mientras la población crecía. Tecnologías de riego israelíes operan hoy en 150 países. El sector agua generó exportaciones por USD 2.200 millones en 2023. Lección transferible a Santander: Especialmente relevante para las zonas semiáridas del Chicamocha (García Rovira, Comunera), donde la escasez hídrica estructural requiere enfoques de eficiencia extrema más que solo restauración. La lógica de gestionar el agua como bien estratégico con tarifación real es aplicable a la reforma del sistema de acueductos rurales y al P01 (Plan Maestro Hídrico). Conexión en Santander 2050: P01 Plan Maestro Hídrico · P04 Red monitoreo · P07 Riego tecnificado · Motor B.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'Mekorot (Fuente 1)', url: 'https://www.mekorot-int.com/', nota: 'Empresa nacional de agua y gestion integral.' },
        { titulo: 'IDE Water Technologies (Fuente 2)', url: 'https://ide-tech.com/en/', nota: 'Soluciones de desalinizacion y tratamiento.' }
      ]
    },
    m2_1: {
      tipo: 'Mision material - Santander Conectado y Equitativo',
      titulo: 'Pais Vasco - Reconversion territorial y cohesion regional',
      resumen: 'Tipo de caso: Cohesión territorial y desarrollo policéntrico. Problema equivalente: En los años 80, región desindustrializada, con altísimo desempleo (27%), conflicto armado activo (ETA), fragmentación territorial entre Bilbao, Vitoria y San Sebastián. ¿Qué hicieron?: Crearon el Plan Estratégico del País Vasco con visión de largo plazo supraelectoral. Invirtieron masivamente en infraestructura intermodal (metro, tren de alta velocidad, puertos). Desarrollaron polos de innovación en cada ciudad-provincia. El proyecto Bilbao Metrópoli-30 articuló lo urbano, rural e industrial en una sola narrativa territorial. Instrumento central: Concierto Económico (autonomía fiscal real), planificación supraelectoral, inversión pública en infraestructura y política de cohesión territorial activa. Resultados verificados: Desempleo bajó del 27% al 8% en 20 años. PIB per cápita 30% por encima de la media española. Modelo de gobernanza territorial replicado en 40 regiones europeas. Lección transferible a Santander: El modelo vasco de desarrollo policéntrico es directamente inspirador para la arquitectura de M2. La lógica de conectar provincias diversas con infraestructura compartida y proyectos áncora por subregión replica el espíritu del clúster Conectividad Territorial. Conexión en Santander 2050: P13 Red vial · P14 Fibra óptica · P17-P22 Nodos provinciales · Motor H.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'Gobierno Vasco (Fuente 1)', url: 'https://www.bm30.eus/antecedentes/', nota: 'Politica regional e institucionalidad.' },
        { titulo: 'Bilbao Metrópoli-30 (Fuente 2)', url: 'https://www.bilbaoturismo.net/BilbaoTurismo/es/personajes-ilustres', nota: 'Contexto de transformacion del territorio.' }
      ]
    },
    m2_2: {
      tipo: 'Mision material - Santander Conectado y Equitativo',
      titulo: 'Uruguay - Plan Ceibal',
      resumen: 'Tipo de caso: Conectividad digital rural universal, equidad educativa y reducción de brechas territoriales. Problema equivalente: País con alta desigualdad digital campo-ciudad: estudiantes rurales sin acceso a tecnología, docentes sin formación digital y brecha educativa creciente entre zonas urbanas y departamentos del interior. ¿Qué hicieron?: Desde 2007, el Plan Ceibal entregó una laptop (luego tablet) a cada estudiante y docente público del país, desplegó conectividad WiFi en todos los centros educativos, creó una plataforma digital de aprendizaje adaptativo (CREA), formó a todos los maestros en competencias digitales y construyó centros de innovación territorial. En 2023, el Plan evolucionó hacia IA educativa con el sistema de tutores adaptativos. Todo sin costo para las familias. Gestión: ente autónomo con presupuesto propio, no dependiente de ministerio educativo. Instrumento central: Ente autónomo con mandato digital-educativo, dispositivo universal garantizado por el Estado, plataforma de aprendizaje adaptativo, formación docente continua y centros de innovación territorial en zonas rurales. Resultados verificados: Uruguay es el país con mayor equidad digital de América Latina (UNESCO, 2022). Brecha de acceso digital campo-ciudad prácticamente eliminada. 750.000 dispositivos entregados. El modelo fue adoptado por 30 países como referente. Reducción del 40% en brecha de aprendizaje matemático urbano-rural en 10 años. Lección transferible a Santander: Plan Ceibal es el referente latinoamericano más directo y contextualmente cercano para el P14 (Fibra Óptica y Aldeas Digitales 5G) y el P42 (Centro de Innovación Educativa Digital UIS-Provincias). La lógica de ente autónomo con mandato digital es transferible para la gobernanza de la conectividad universal en Santander. Conexión en Santander 2050: P14 Fibra óptica · P42 UIS-Provincias · P20 Aldeas Digitales · Motor C · SB4 Ecosistema Talento.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'Plan Ceibal (Fuente 1)', url: 'https://ceibal.edu.uy/', nota: 'Plataforma de inclusion digital educativa.' },
        { titulo: 'UNICEF - Plan Ceibal (Fuente 2)', url: 'https://bibliotecaunicef.uy/opac_css/index.php?lvl=publisher_see&id=60', nota: 'Analisis de impacto y equidad.' }
      ]
    },
    m2_3: {
      tipo: 'Mision material - Santander Conectado y Equitativo',
      titulo: 'Programa LEADER en Union Europea',
      resumen: 'Tipo de caso: Desarrollo rural policéntrico y cohesión territorial. Problema equivalente: Despoblación y atraso crónico de zonas rurales europeas frente a metrópolis, con pérdida de servicios, empleo y cultura local. ¿Qué hicieron?: Desde 1991, el programa LEADER financia Grupos de Acción Local (GAL) en territorios rurales que diseñan su propia estrategia de desarrollo con fondos europeos. Cada GAL articula municipios, empresas, academia y comunidades en una visión territorial compartida. Ha operado en 2.800 territorios en 30 países. Instrumento central: Grupos de Acción Local con personería jurídica, estrategia territorial propia y financiamiento condicionado a resultados medibles. Resultados verificados: Más de 360.000 proyectos rurales financiados en 30 años. Revirtió la despoblación en 40% de los territorios donde operó. Generó el modelo de gobernanza territorial más replicado del mundo. Lección transferible a Santander: Los GAL del programa LEADER son el referente conceptual más directo para el diseño de los Laboratorios Vivos Territoriales SB1-SB5 de Santander y para la arquitectura del SSITD provincial. Conexión en Santander 2050: P17-P22 Nodos provinciales · P36-P37 SSITD · SB1-SB5 Laboratorios · Motor G.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'LEADER/CLLD (Fuente 1)', url: 'https://eu-cap-network.ec.europa.eu/', nota: 'Metodologia de desarrollo local participativo.' },
        { titulo: 'EU Rural Development (Fuente 2)', url: 'https://agriculture.ec.europa.eu/common-agricultural-policy/rural-development_en', nota: 'Politica y financiamiento rural europeo.' }
      ]
    },
    m3_1: {
      tipo: 'Mision material - Reconversion Productiva y Energetica',
      titulo: 'Ruhr Alemania - Reconversion post extractiva',
      resumen: 'Tipo de caso: Transición post-extractiva y reconversión productiva territorial. Problema equivalente: Región minera e industrial más importante de Europa en declive: cierre de minas de carbón, 500.000 empleos perdidos, contaminación extrema, éxodo de talento, colapso fiscal de municipios. ¿Qué hicieron?: El gobierno estatal creó la Internationale Bauausstellung (IBA Emscher Park): un proyecto de reconversión territorial de 10 años con 120 proyectos simultáneos. Transformó infraestructura industrial en parques, centros culturales y clústeres tecnológicos. Creó el Fondo de Transición Justa con participación activa de sindicatos y comunidades mineras. Reindustrialización verde con química, energías renovables y economía creativa. Instrumento central: Fondo de transición con financiamiento federal y estatal, conversión de pasivos industriales en activos culturales, clústeres de reindustrialización verde y pacto territorial multiactor. Resultados verificados: Región pasó de mayor contaminación en Europa a destino cultural de 5 millones de turistas/año. 200.000 nuevos empleos en sectores verdes y creativos. Modelo replicado en 25 regiones extractivas del mundo. Lección transferible a Santander: El caso Ruhr es el referente más directo para la reconversión del Magdalena Medio santandereano. La lógica del IBA Emscher Park puede inspirar el diseño del SB2 (Magdalena Medio 4.0) y el Distrito Industrial de Transición Energética (P23). Conexión en Santander 2050: P23 Distrito Transición · P24 Parque industrial · SB2 Magdalena Medio 4.0 · Motor A · Motor D.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'IBA Emscher Park (Fuente 1)', url: 'https://www.internationale-bauausstellungen.de/en/history/1989-1999-iba-emscher-park-a-future-for-an-industrial-region/', nota: 'Caso emblematico de regeneracion industrial.' },
        { titulo: 'Just Transition Fund UE (Fuente 2)', url: 'https://commission.europa.eu/strategy-and-policy/priorities-2019-2024/european-green-deal/finance-and-green-deal/just-transition-mechanism_en', nota: 'Instrumento de financiacion para transicion justa.' }
      ]
    },
    m3_2: {
      tipo: 'Mision material - Reconversion Productiva y Energetica',
      titulo: 'Dinamarca - Transicion energetica territorial',
      resumen: 'Tipo de caso: Transición energética justa a escala territorial. Problema equivalente: Dependencia del carbón y el petróleo con altos costos energéticos y emisiones, afectando tanto la competitividad industrial como las comunidades rurales e isleñas. ¿Qué hicieron?: La isla de Samsø se convirtió en 1997 en laboratorio de transición energética 100% renovable en 10 años, con propiedad comunitaria de aerogeneradores y biomasa. Bornholm (isla de 40.000 habitantes) fue declarada zona de experimentación regulatoria (sandbox energético) con 50% de renovables y gestión inteligente de la red. Instrumento central: Laboratorio territorial con excepción regulatoria, propiedad comunitaria de infraestructura energética, fondo de inversión cooperativo y monitoreo en tiempo real. Resultados verificados: Samsø exporta energía renovable equivalente al 100% de su consumo. Bornholm redujo costos energéticos en 35%. El modelo generó 12 clústeres de energía comunitaria similares en Europa. Lección transferible a Santander: El modelo Samsø/Bornholm es el referente conceptual más preciso para el diseño del SB2 (Magdalena Medio 4.0) como sandbox energético territorial. La propiedad comunitaria de infraestructura renovable es transferible al contexto del Magdalena Medio. Conexión en Santander 2050: P23 Distrito Transición · SB2 Magdalena Medio 4.0 · Motor A · P25 Energía renovable.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'Energiakademiet (Fuente 1)', url: 'https://www.energiakademiet.dk/en/', nota: 'Laboratorio territorial de energia comunitaria.' },
        { titulo: 'Energy Island (Fuente 2)', url: 'https://bornholmenergyisland.eu/en/', nota: 'Estrategia danesa de infraestructura energetica.' }
      ]
    },
    m3_3: {
      tipo: 'Mision material - Reconversion Productiva y Energetica',
      titulo: 'Wageningen - Bioeconomia circular agricola',
      resumen: 'Tipo de caso: Bioeconomía avanzada y agroindustria de alto valor. Problema equivalente: País pequeño y densamente poblado sin recursos naturales abundantes, que necesitaba construir una ventaja competitiva basada en conocimiento agrícola y no en escala territorial. ¿Qué hicieron?: Crearon el clúster Food Valley en torno a la Universidad de Wageningen: ecosistema de 1.500 empresas agroalimentarias, 15.000 investigadores y conexión directa entre universidad, empresa y gobierno. Toda la cadena de valor agrícola se basó en innovación, trazabilidad y valor agregado. Agricultura circular con reutilización del 98% de residuos. Instrumento central: Triple Hélice universidad-empresa-gobierno en un ecosistema territorial de innovación, con laboratorios de experimentación abierta y plataforma de datos compartidos. Resultados verificados: Países Bajos es el 2.º exportador mundial de alimentos, con solo 0,3% de la tierra agrícola mundial. Wageningen Universidad lidera el ranking global en ciencias agronómicas. Food Valley exportó el modelo a 30 países. Lección transferible a Santander: Food Valley es el referente del Motor B y el clúster BioSantander (P26). La triple hélice UIS-empresa-gobierno es el modelo organizacional para el Ecosistema BioSantander. Conexión en Santander 2050: P26 BioSantander · P27 Agricultura regenerativa · Motor B · SB1 BioRegión.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'Foodvalley (Fuente 1)', url: 'https://www.foodvalley.nl/en/', nota: 'Cluster de innovacion agroalimentaria.' },
        { titulo: 'WUR Food & Biobased Research (Fuente 2)', url: 'https://www.wur.nl/en/research-results/research-institutes/food-biobased-research', nota: 'Investigacion aplicada en bioeconomia.' }
      ]
    },
    m3_4: {
      tipo: 'Mision material - Reconversion Productiva y Energetica',
      titulo: 'Noruega - Fondo soberano del petroleo',
      resumen: 'Tipo de caso: Transición desde economía extractiva: captura de renta y diversificación productiva. Problema equivalente: Descubrimiento masivo de petróleo en los años 70 con riesgo de \'enfermedad holandesa\': sobreapreciación de la moneda, desindustrialización, dependencia del recurso y colapso económico proyectado cuando el petróleo se agotara. ¿Qué hicieron?: Crearon en 1990 el Fondo Global del Gobierno (Government Pension Fund Global), el fondo soberano más grande del mundo. En lugar de gastar los ingresos petroleros en el presente, los invierten en activos globales y solo usan el retorno estimado del 3% anual en el presupuesto público. Paralelamente, transformaron la empresa estatal Equinor de petrolera a empresa de energía diversificada (eólica marina, hidrógeno, captura de carbono). Invirtieron masivamente en formación tecnológica, acuicultura y política industrial no petrolera. Instrumento central: Regla fiscal de ahorro soberano con techo de gasto, fondo de inversión global con transparencia parlamentaria total, política de diversificación productiva financiada con retornos del fondo y transformación de la empresa estatal hacia energía diversificada. Resultados verificados: El fondo vale hoy USD 1,7 billones — el mayor fondo soberano del mundo. Noruega tiene el PIB per cápita más alto de Europa y cero deuda pública neta. La economía no petrolera representa el 75% del PIB. Equinor opera en 30 países en energías renovables. Lección transferible a Santander: El caso noruego es el referente estratégico más potente para los gremios del sector petrolero del Magdalena Medio. La pregunta clave que plantea para Santander es: ¿cómo capturar una fracción de la renta del petróleo restante para financiar la transición hacia los motores de desarrollo 2050 antes de que esa renta se agote? Directo para el diseño del Fondo de Transición Energética del SB2 y el P31. Conexión en Santander 2050: SB2 Magdalena Medio 4.0 · P23 Distrito Transición · P31 Fondo Innovación · Motor A.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'NBIM (Fuente 1)', url: 'https://www.nbim.no/en/', nota: 'Gestor del fondo soberano noruego.' },
        { titulo: 'Norges Bank - Oil Fund (Fuente 2)', url: 'https://www.norges-bank.no/en/topics/Monetary-policy/oil-fund/', nota: 'Marco institucional y fiscal del fondo.' }
      ]
    },
    m4_1: {
      tipo: 'Mision habilitante - Inteligencia Territorial y Gobernanza Participativa',
      titulo: 'Estonia - Gobierno digital y datos',
      resumen: 'Tipo de caso: Gobierno digital, inteligencia territorial e interoperabilidad. Problema equivalente: País pequeño post-soviético (1,4 millones de habitantes) con instituciones débiles, baja capacidad de gestión pública y necesidad de transformación rápida sin recursos abundantes. ¿Qué hicieron?: Desde 1997, construyeron e-Estonia: identidad digital universal, plataforma X-Road de interoperabilidad de datos públicos, votación electrónica, declaraciones de impuestos en 3 minutos, empresa registrada en 18 minutos. 99% de servicios gubernamentales disponibles en línea. Crearon el concepto de \'datos una vez\': el ciudadano nunca repite información al Estado. Instrumento central: Legislación de identidad digital, plataforma de interoperabilidad abierta X-Road, inversión continua en infraestructura digital pública y cultura de innovación gubernamental. Resultados verificados: Estado más eficiente de Europa (índice OCDE). Ahorro anual del 2% del PIB en costos administrativos. El modelo X-Road fue adoptado por Finlandia, Japón y la UE. E-residency ha atraído 100.000 emprendedores globales. Lección transferible a Santander: Estonia es el referente directo para el Gemelo Digital (P34), la Plataforma de Datos Territoriales y el motor de Gobernanza e Inteligencia Territorial (Motor G). La lógica de X-Road puede inspirar el diseño del SSITD de Santander. Conexión en Santander 2050: P34 Gemelo Digital · P35 Consejo Futuro · P36 SSITD · Motor G · SB3 Inteligencia Territorial.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'e-Estonia (Fuente 1)', url: 'https://e-estonia.com/', nota: 'Marco de gobierno digital nacional.' },
        { titulo: 'X-Road (Fuente 2)', url: 'https://www.ria.ee/en/x-road.html', nota: 'Intercambio seguro de datos del Estado.' }
      ]
    },
    m4_2: {
      tipo: 'Mision habilitante - Inteligencia Territorial y Gobernanza Participativa',
      titulo: 'Medellin - Urbanismo social y gobernanza participativa',
      resumen: 'Tipo de caso: Gobernanza participativa, cohesión social y transformación urbano-rural. Problema equivalente: Ciudad con la tasa de homicidios más alta del mundo en los años 90, fragmentación territorial extrema entre comunas, instituciones capturadas y brechas sociales estructurales. ¿Qué hicieron?: Crearon el modelo de Urbanismo Social: intervención simultánea en infraestructura (metrocable, parques biblioteca, escaleras eléctricas), instituciones (escuelas, centros de salud) y participación comunitaria en zonas de exclusión. Laboratorio de Medellín (Ruta N) como ecosistema de innovación. Presupuesto participativo con trazabilidad digital. Instrumento central: Planeación participativa por zonas, inversión pública focalizada en territorios de exclusión, ecosistema de innovación (Ruta N) y presupuesto participativo con rendición de cuentas pública. Resultados verificados: Reducción del 95% en tasa de homicidios entre 1991 y 2015. Premio a la ciudad más innovadora del mundo (2013). Modelo exportado a 30 ciudades latinoamericanas. IDH aumentó del 0,62 al 0,81 en 20 años. Lección transferible a Santander: El modelo Ruta N y el Presupuesto Participativo son los referentes más directos para el P38 (Alianza por Santander) y el P35 (Consejo de Futuro). El urbanismo social es transferible al diseño de los Nodos Provinciales de Innovación. Conexión en Santander 2050: P35 Consejo Futuro · P38 Alianza Santander · P17-P22 Nodos · Motor G · SB3.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'Ruta N Medellin (Fuente 1)', url: 'https://www.rutanmedellin.org/', nota: 'Ecosistema de innovacion y desarrollo urbano.' },
        { titulo: 'PNUD Medellin (Fuente 2)', url: 'https://www.undp.org/es/colombia/proyectos/alianza-epm-pnud', nota: 'Lectura de transformacion territorial.' }
      ]
    },
    m4_3: {
      tipo: 'Mision habilitante - Inteligencia Territorial y Gobernanza Participativa',
      titulo: 'Barcelona/Helsinki - Gemelos digitales territoriales',
      resumen: 'Tipo de caso: Inteligencia territorial, simulación urbana y gobernanza basada en datos en tiempo real. Problema equivalente: Ciudades con complejidad creciente de decisiones públicas (movilidad, energía, agua, servicios) sin capacidad de simular el impacto de políticas antes de implementarlas, con alto riesgo de inversiones mal orientadas y baja confianza ciudadana. ¿Qué hicieron?: Barcelona creó el proyecto CityOS / Sentilo: plataforma de datos urbanos en tiempo real con 1.300 sensores IoT integrados (ruido, tráfico, residuos, agua, energía) y un modelo 3D del territorio que permite simular impactos de decisiones antes de ejecutarlas. Helsinki construyó Helsinki 3D+: gemelo digital completo de la ciudad con datos de movilidad, clima, infraestructura y servicios integrados, accesible al público. Ambas ciudades articularon su gemelo digital con presupuesto participativo: los ciudadanos pueden ver simulaciones del impacto de inversiones antes de votar. Instrumento central: Plataforma de datos territoriales en tiempo real con sensórica IoT, modelo 3D simulable del territorio, interoperabilidad entre sistemas de la ciudad, acceso público a datos y vinculación del gemelo con decisiones presupuestarias participativas. Resultados verificados: Barcelona redujo el consumo de agua en un 25% y los costos de mantenimiento de infraestructura en un 20% usando datos del gemelo. Helsinki es la ciudad con mayor transparencia de datos públicos del mundo (Open Data Index). El modelo Barcelona Sentilo fue adoptado por 12 ciudades europeas y latinoamericanas, incluyendo Bogotá. Lección transferible a Santander: Barcelona/Helsinki es el referente operativo más preciso para el P34 (Gemelo Digital Territorial / Plataforma de Datos Santander 2050). La arquitectura Sentilo es código abierto y fue adaptada en Bogotá, lo que indica viabilidad de transferencia directa a un contexto colombiano. El vínculo entre gemelo digital y presupuesto participativo es directamente aplicable al Consejo de Futuro (P35) y la Alianza por Santander (P38). Conexión en Santander 2050: P34 Gemelo Digital · P35 Consejo Futuro · P36 SSITD · P38 Alianza Santander · Motor G · SB3 Inteligencia Territorial.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'Sentilo (Fuente 1)', url: 'https://sentilo.io/', nota: 'Plataforma abierta de sensores urbanos.' },
        { titulo: 'Helsinki 3D Data (Fuente 2)', url: 'https://www.hel.fi/en/decision-making/information-on-helsinki/maps-and-geospatial-data/helsinki-3d', nota: 'Modelado urbano digital para planificacion.' }
      ]
    },
    m5_1: {
      tipo: 'Mision habilitante - Educacion, Cultura y Talento',
      titulo: 'Finlandia - Sistema educativo con enfoque territorial',
      resumen: 'Tipo de caso: Sistema educativo para la innovación, equidad y retención de talento. Problema equivalente: En los años 70, sistema educativo desigual con grandes brechas entre zonas urbanas y rurales, y escasa conexión entre educación y economía productiva. ¿Qué hicieron?: Reforma educativa de largo plazo con base en equidad territorial: toda escuela, sin importar su ubicación, debe tener el mismo nivel de calidad. Eliminación de rankings escolares. Formación docente al nivel de maestría universitaria. Currículum flexible con énfasis en resolución de problemas y colaboración. Educación como bien público universal sin costos. Instrumento central: Reforma sistémica de 30 años con consenso político supraelectoral, inversión equitativa por territorio (no por impuesto local), autonomía pedagógica y evaluación formativa. Resultados verificados: 1.º del mundo en PISA durante una década. Brecha educativa entre zonas rurales y urbanas menor que en cualquier país OCDE. 66% de adultos con educación terciaria. Modelo exportado a Singapur, Corea y Estonia. Lección transferible a Santander: El modelo finlandés de equidad territorial educativa es el referente para el diseño de la Red de Campus Territoriales (P40) y la política de retención de talento en provincias. La autonomía pedagógica es transferible al diseño curricular de los campus provinciales. Conexión en Santander 2050: P40 Campus territoriales · P41 Talento Santander Global · Motor C · SB4 Ecosistema Talento.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'Finnish National Agency for Education (Fuente 1)', url: 'https://www.oph.fi/en/education-system', nota: 'Estructura y principios del sistema educativo.' },
        { titulo: 'Ministry of Education Finland (Fuente 2)', url: 'https://okm.fi/en/frontpage', nota: 'Politica publica educativa nacional.' }
      ]
    },
    m5_2: {
      tipo: 'Mision habilitante - Educacion, Cultura y Talento',
      titulo: 'Medellin - Economia naranja y cluster creativo',
      resumen: 'Tipo de caso: Economía cultural, industrias creativas y retención de talento joven. Problema equivalente: Necesidad de diversificar la economía más allá de manufactura y servicios tradicionales, retener talento joven y generar empleos de calidad para población vulnerable. ¿Qué hicieron?: Desarrollaron el Distrito Creativo Ciudad del Río y el Parque del Emprendimiento. Crearon las políticas de Economía Naranja (cultura, diseño, audiovisual, software creativo) con incentivos tributarios, espacios de coworking subsidiados y fondo de capital semilla. La Fiducia Social articuló universidad-empresa-comunidad en proyectos creativos de barrio. Instrumento central: Distrito creativo territorial con incentivos, fondo de capital semilla, programa de formación articulado con demanda empresarial y ecosistema físico de innovación. Resultados verificados: Medellín concentra el 25% de la producción audiovisual de Colombia. Exportaciones de servicios creativos: USD 180 millones anuales. 40.000 empleos en economía naranja con salarios 40% por encima del promedio. Lección transferible a Santander: El modelo Economía Naranja de Medellín es el referente más directo para el Plan de Cultura y Creatividad Santander Viva (P43) y el Motor F (Turismo de alto valor y economía cultural). La estructura del Distrito Creativo puede inspirar los Nodos Provinciales. Conexión en Santander 2050: P43 Cultura Santander Viva · Motor F · P17-P22 Nodos · SB4 Ecosistema Talento.',
      fuente: 'Fuente: Volumen I en Enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'Economía Naranja Medellín (Fuente 1)', url: 'https://acimedellin.org/medellin-trabaja-para-dinamizar-la-economia-naranja/', nota: 'Politicas y acciones del distrito creativo.' },
        { titulo: 'OECD Territorial Review Medellin (Fuente 2)', url: 'https://www.oecd.org/en/about/programmes/leed-programme.html', nota: 'Evaluacion internacional del modelo territorial.' }
      ]
    },
    m5_3: {
      tipo: 'Mision habilitante - Educacion, Cultura y Talento',
      titulo: 'Singapur - SkillsFuture',
      resumen: 'Tipo de caso: Formación técnica y profesional para la transformación productiva. Problema equivalente: Ciudad-estado sin recursos naturales ni territorio que necesitaba construir una economía basada exclusivamente en capital humano y conocimiento para competir globalmente. ¿Qué hicieron?: Crearon SkillsFuture: programa nacional de formación continua con crédito individual para toda la población adulta ($500 SGD/persona/año actualizable), articulado con demanda empresarial real. Institutos Politécnicos diseñados por industria. Programa ReSkillingSG para transiciones productivas. Toda la formación técnica está conectada con la hoja de ruta económica del país. Instrumento central: Crédito individual universal de formación, institutos técnicos codiseñados por empresas, programa de reconversión laboral y sistema de certificación nacional. Resultados verificados: 75% de adultos en formación continua. Empleabilidad técnica del 96%. Tasa de retención de talento local del 92%. Singapur está clasificado entre los 3 países más competitivos del mundo (WEF, 2024). Lección transferible a Santander: SkillsFuture es el referente para el Programa Talento Santander Global (P41) y el diseño de los Campus Territoriales de Innovación (P40). La lógica de formación orientada por demanda productiva es aplicable directamente al diseño curricular de los 8 motores. Conexión en Santander 2050: P40 Campus territoriales · P41 Talento Global · P42 UIS Provincias · SB4 Ecosistema Talento · Motor C.',
      fuente: 'Fuente: Volumen I en enlaces_Referentes_Santander2050_v2.docx/.pdf',
      enlaces: [
        { titulo: 'SkillsFuture (Fuente 1)', url: 'https://www.skillsfuture.gov.sg/', nota: 'Programa nacional de aprendizaje permanente.' },
        { titulo: 'Workforce Singapore (Fuente 2)', url: 'https://www.wsg.gov.sg/home/employers-industry-partners/workforce-development-job-redesign/career-conversion-programmes-employers', nota: 'Ruta de habilidades y empleabilidad.' }
      ]
    }
  };
})();
